"""Anthropic Claude integration — mandatory design judge over every carousel.

Claude no longer acts as a fallback. After DeepSeek drafts the carousel, Claude
ALWAYS reviews every slide as a senior art director + prompt engineer and
returns a refined, FLUX-ready prompt set. This is intentional: DeepSeek is fast
and cheap but its prompts often drift from the topic, ignore typography rules,
or generate text strings FLUX cannot render legibly. Claude tightens all of
that before we burn money on image generation.
"""

from __future__ import annotations

import json
import time
from typing import Any

import anthropic
from tenacity import retry, stop_after_attempt, wait_exponential

from app.config import settings
from app.utils.costs import record_cost
from app.utils.logging import get_logger

logger = get_logger(__name__)

_MODEL = "claude-sonnet-4-5"
_MAX_TOKENS = 4000

_JUDGE_SYSTEM = """\
You are a senior art director, prompt engineer, and quality judge for viral
Instagram carousels generated by FLUX Pro Ultra. A junior model (DeepSeek)
already drafted a full carousel. Your job is to AUDIT every slide and return
a polished, production-ready set. You are the last line of defense before we
spend money rendering images.

You will receive:
- brand, brand_palette, brand_voice, instagram_handle
- selected_topic (title + summary) and theme_seed — these define WHAT the
  images must depict
- visual_style (key, label, prompt_hint) — defines aesthetics ONLY
- caption_language — language for story_text and caption
- slides — the draft set produced by DeepSeek
- validator_signal — local quality scores (informational, not a gate)

YOUR JOB (in order):

1. JUDGE EVERY SLIDE. For each slide, silently check:
   - Subject fidelity: does the prompt clearly depict the selected_topic
     (title + summary), not just generic style? Reject vague scenes.
   - Narrative role: hook hooks, dev advances, cta closes. Re-assign if
     a slide is mislabeled.
   - In-image typography: is story_text 3-12 words, in caption_language,
     ALL CAPS or Title Case, and short enough for FLUX to render legibly?
   - Prompt-text alignment: does the FLUX `prompt` instruct it to render
     EXACTLY the story_text via `rendered_text: "<story_text>"`? Does it
     reserve clear negative space for that text?
   - Color contrast: is text_color from the brand_palette OR a neutral
     chosen for WCAG-AA contrast against the dominant area described in
     the prompt? Reject low-contrast picks (e.g. light gray on white,
     dark blue on black).
   - Brand alignment: scene, mood, palette, and voice all consistent
     with brand_palette and brand_voice.
   - Cross-slide cohesion: recurring visual elements, consistent
     palette, consistent character/object continuity in >=60% of slides.
     No two prompts may describe near-identical scenes.
   - FLUX failure modes: avoid prompts asking for >12 words of rendered
     text, complex tables, dense numerals, foreign scripts mixed with
     latin, tiny text, or text on busy backgrounds.

2. REWRITE WHAT YOU FAIL. For every slide that fails any check, rewrite
   the offending fields. For slides that pass, you may still tighten
   wording for clarity, but do not change story_text or text_color
   gratuitously. Keep slide numbers stable (1..N).

3. ENFORCE THE SCHEMA. Every returned slide MUST have:
   - slide (int, 1..N)
   - role (hook | dev1 | dev2 | ... | cta)
   - story_text (caption_language, 3-12 words, headline that goes INSIDE
     the image)
   - text_color (hex like "#0A0A0A", from brand_palette or a justified
     neutral)
   - text_weight ("Bold" | "SemiBold" | "Regular")
   - prompt (ENGLISH, 90-170 words, fed directly to FLUX Pro Ultra,
     ending with `aspect ratio 4:5`)
   - caption (caption_language, 40-80 words, the Instagram caption —
     NOT the in-image text)
   - judge_notes (1-2 short sentences in English describing what you
     fixed or, if untouched, why it already passed)

4. FLUX TYPOGRAPHY CONTRACT. Inside every `prompt` you MUST include,
   verbatim or paraphrased but unambiguous:
   - rendered_text: "<exact story_text>"
   - typeface "Montserrat" with the matching weight
   - text color expressed as BOTH hex and a short descriptive name
     (e.g. "#0A0A0A deep charcoal")
   - explicit contrast strategy against the described scene
   - explicit negative-space placement for the text (top third, bottom
     third, left margin, semi-transparent band, etc.)
   - high-quality kerning, crisp letterforms, no spelling mistakes

5. STORY ARC. Also return a refined `story_arc` (1 sentence in English)
   describing the narrative across the polished slides.

HARD RULES:
- Preserve theme_seed and selected_topic. The carousel is about that
  subject. Visual style only controls aesthetics.
- All story_text and caption strings are in caption_language. Never mix
  languages inside a single string.
- Never invent new brands, products, hashtags, or accounts.
- Reject and rewrite any slide whose prompt is generic, low-contrast,
  topic-drifting, or asks FLUX to render long/complex text.
- Be opinionated. You are the judge. If DeepSeek delivered 5 weak
  slides, return 5 strong ones.

OUTPUT FORMAT — respond ONLY with a single valid JSON object, no
markdown, no commentary:

{
  "story_arc": "...",
  "slides": [
    {
      "slide": 1,
      "role": "hook",
      "story_text": "...",
      "text_color": "#RRGGBB",
      "text_weight": "Bold",
      "prompt": "...",
      "caption": "...",
      "judge_notes": "..."
    }
  ]
}
"""


@retry(stop=stop_after_attempt(2), wait=wait_exponential(multiplier=1, min=3, max=20))
async def judge_and_polish_prompts(
    slides: list[dict[str, Any]],
    story_arc: str,
    theme_seed: str,
    topic: dict[str, str],
    visual_style: dict[str, Any],
    caption_language: str,
    brand_name: str,
    brand_preset: dict[str, Any],
    validator_signal: dict[str, Any],
    flow_id: str,
) -> dict[str, Any]:
    """Run Claude as senior art director over the full draft carousel.

    Always called after DeepSeek. Returns a polished
    ``{"story_arc": str, "slides": list[dict]}`` ready for image generation.

    Args:
        slides: Draft slide dicts from DeepSeek.
        story_arc: Draft narrative arc from DeepSeek.
        theme_seed: User-provided seed that anchors the subject.
        topic: Selected topic ({"title": ..., "summary": ...}).
        visual_style: ``{"key", "label", "prompt_hint"}``.
        caption_language: Language for story_text and caption strings.
        brand_name: Brand identifier.
        brand_preset: Full brand preset (palette, voice, handle, etc.).
        validator_signal: Local validator output for context.
        flow_id: For cost tracking and log correlation.
    """
    user_payload = {
        "brand": brand_name,
        "instagram_handle": brand_preset.get("instagram_handle"),
        "brand_palette": brand_preset.get("palette", {}),
        "brand_voice": brand_preset.get("voice", {}),
        "theme_seed": theme_seed,
        "selected_topic": topic,
        "visual_style": visual_style,
        "caption_language": caption_language,
        "story_arc": story_arc,
        "slides": slides,
        "validator_signal": validator_signal,
    }
    user_content = json.dumps(user_payload, ensure_ascii=False)

    client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)

    start = time.monotonic()
    message = await client.messages.create(
        model=_MODEL,
        max_tokens=_MAX_TOKENS,
        system=_JUDGE_SYSTEM,
        messages=[{"role": "user", "content": user_content}],
    )
    latency_ms = int((time.monotonic() - start) * 1000)

    usage = message.usage
    # Rough cost estimate: ~$3 / 1M input tokens, ~$15 / 1M output tokens
    cost = (usage.input_tokens * 3 + usage.output_tokens * 15) / 1_000_000

    await record_cost(
        flow_id=flow_id,
        service="anthropic",
        model=_MODEL,
        tokens_input=usage.input_tokens,
        tokens_output=usage.output_tokens,
        cost_usd=cost,
        latency_ms=latency_ms,
    )

    raw = message.content[0].text  # type: ignore[union-attr]
    polished: dict[str, Any] = json.loads(raw)

    polished_slides = polished.get("slides", [])
    if not isinstance(polished_slides, list) or not polished_slides:
        # Defensive: if Claude returned nothing usable, keep DeepSeek draft.
        logger.warning(
            "claude_judge_returned_empty",
            flow_id=flow_id,
            tokens_in=usage.input_tokens,
            tokens_out=usage.output_tokens,
        )
        return {"story_arc": story_arc, "slides": slides}

    logger.info(
        "prompts_polished_by_claude",
        flow_id=flow_id,
        slide_count=len(polished_slides),
        tokens_in=usage.input_tokens,
        tokens_out=usage.output_tokens,
        latency_ms=latency_ms,
    )

    return {
        "story_arc": polished.get("story_arc", story_arc),
        "slides": polished_slides,
    }
